`timescale 1ns / 1ps

// register_file UVM Package
// Generated by UVM Base Generator on 2025-07-27 21:05:11
package register_file_pkg;
    
    // UVM is available with -uvm flag in DSIM
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Include all UVM components with organized directory structure
    `include "../transactions/register_file_transaction.sv"
    `include "../sequences/register_file_sequence.sv"
    `include "../agents/register_file_driver.sv"
    `include "../agents/register_file_monitor.sv"
    `include "../agents/register_file_agent.sv"
    `include "../env/register_file_env.sv"
    `include "../tests/register_file_test.sv"
    
endpackage
