// File list for register_file UVM testbench
// Generated by UVM Base Generator with organized directory structure

// RTL files first (interfaces must be compiled before packages that use them)
..\..\rtl\interfaces\register_file_if.sv
..\..\rtl\hdl\register_file.sv

// UVM package file (contains all UVM components)
..\uvm\base\register_file_pkg.sv

// Testbench top
..\tb\register_file_tb.sv
