// File list for register_file UVM testbench
// Generated by UVM Base Generator with organized directory structure

// RTL files first (interfaces must be compiled before packages that use them)
..\..\rtl\interfaces\register_file_if.sv
..\..\rtl\hdl\register_file.sv

// UVM library (use DSIM built-in UVM)
-uvm

// Testbench top (includes UVM package directly)
..\tb\register_file_tb.sv
