@echo off
REM Unified Test Execution Script for register_file
REM Generated by UVM Base Generator - Based on DSIMtuto best practices
REM Usage: run.bat [test_name]

setlocal enabledelayedexpansion

REM Configuration file
set CONFIG_FILE=test_config.cfg

REM Check if test name is provided
if "%1"=="" (
    echo.
    echo ================================
    echo   REGISTER_FILE Test Runner
    echo ================================
    echo.
    echo Usage: run.bat [test_name]
    echo.
    echo Available tests:
    echo ----------------
    for /f "eol=# tokens=1,2 delims=|" %%a in (%CONFIG_FILE%) do (
        echo   %%a - %%b
    )
    echo.
    goto :eof
)

set TEST_NAME=%1

REM Parse configuration file to find test
set FOUND=0
for /f "eol=# tokens=1,2,3,4,5,6 delims=|" %%a in (%CONFIG_FILE%) do (
    if "%%a"=="%TEST_NAME%" (
        set FOUND=1
        set TEST_DESC=%%b
        set FILELIST=%%c
        set TEST_CLASS=%%d
        set WAVE_FILE=%%e
        set VERBOSITY=%%f
    )
)

if %FOUND%==0 (
    echo ERROR: Test '%TEST_NAME%' not found in configuration
    echo Run 'run.bat' to see available tests
    exit /b 1
)

REM DSIM Environment Setup
set "DSIM_LICENSE=%USERPROFILE%\AppData\Local\metrics-ca\dsim-license.json"
call "%USERPROFILE%\AppData\Local\metrics-ca\dsim\20240422.0.0\shell_activate.bat"

REM Check DSIM environment
if not defined DSIM_HOME (
    echo ERROR: DSIM_HOME environment variable not set
    exit /b 1
)

REM Display test information
echo.
echo ================================================================================
echo Test: %TEST_NAME%
echo Description: %TEST_DESC%
echo Filelist: %FILELIST%
echo Test Class: %TEST_CLASS%
echo Wave File: %WAVE_FILE%
echo Verbosity: %VERBOSITY%
echo DSIM_HOME: %DSIM_HOME%
echo ================================================================================
echo.

REM Create waves directory if it doesn''t exist
if not exist waves mkdir waves

REM Execute DSIM simulation with organized include paths
echo Starting DSIM simulation...
dsim ^
    +incdir+../uvm/base +incdir+../uvm/transactions +incdir+../uvm/sequences +incdir+../uvm/agents +incdir+../uvm/env +incdir+../uvm/tests ^
    +incdir+%DSIM_HOME%\uvm\1.2\src ^
    +define+UVM_NO_DEPRECATED ^
    +define+UVM_NO_DPI ^
    +acc+b ^
    -sv ^
    %DSIM_HOME%\uvm\1.2\src\uvm_pkg.sv ^
    ../../rtl/interfaces/register_file_if.sv ^
    ../../rtl/hdl/register_file.sv ^
    ../uvm/base/register_file_pkg.sv ^
    ../tb/register_file_tb.sv ^
    +UVM_TESTNAME=%TEST_CLASS% ^
    +UVM_VERBOSITY=%VERBOSITY% ^
    -waves waves\%WAVE_FILE% ^
    -top register_file_tb

set DSIM_EXIT_CODE=%ERRORLEVEL%

echo.
if %DSIM_EXIT_CODE%==0 (
    echo ================================================================================
    echo Test '%TEST_NAME%' completed successfully!
    echo Waveform saved to: waves\%WAVE_FILE%
    echo ================================================================================
) else (
    echo ================================================================================
    echo Test '%TEST_NAME%' failed with exit code: %DSIM_EXIT_CODE%
    echo Check the simulation log for details
    echo ================================================================================
)

exit /b %DSIM_EXIT_CODE%
