`timescale 1ns / 1ps

// {module_name} UVM Package
// Generated by UVM Base Generator on {timestamp}
package {module_name}_pkg;
    
    // Import UVM package (DSIM provides uvm_pkg with -uvm flag)
    import uvm_pkg::*;
    
    // Include all UVM components with organized directory structure
    `include "../transactions/{module_name}_transaction.sv"
    `include "../sequences/{module_name}_sequence.sv"
    `include "../agents/{module_name}_driver.sv"
    `include "../agents/{module_name}_monitor.sv"
    `include "../agents/{module_name}_agent.sv"
    `include "../env/{module_name}_scoreboard.sv"
    `include "../env/{module_name}_env.sv"
    `include "../tests/{module_name}_test.sv"
    
endpackage
