`timescale 1ns / 1ps

// {module_name} UVM Package
// Generated by UVM Base Generator on {timestamp}
package {module_name}_pkg;
    
    // UVM is available with -uvm flag in DSIM
    `include "uvm_macros.svh"
    
    // Include all UVM components with organized directory structure
    `include "../transactions/{module_name}_transaction.sv"
    `include "../sequences/{module_name}_sequence.sv"
    `include "../agents/{module_name}_driver.sv"
    `include "../agents/{module_name}_monitor.sv"
    `include "../agents/{module_name}_agent.sv"
    `include "../env/{module_name}_env.sv"
    `include "../tests/{module_name}_test.sv"
    
endpackage
