`timescale 1ns / 1ps

// REGISTER_FILE UVM Package
// Generated by UVM Base Generator on 2025-07-27 22:56:19
// UVM macros provided by DSIM -uvm flag
package register_file_pkg;
    
    import uvm_pkg::*;
    
    // Include all UVM components with organized directory structure
    `include "../uvm/transactions/register_file_transaction.sv"
    `include "../uvm/sequences/register_file_sequence.sv"
    `include "../uvm/agents/register_file_driver.sv"
    `include "../uvm/agents/register_file_monitor.sv"
    `include "../uvm/agents/register_file_agent.sv"
    `include "../uvm/env/register_file_env.sv"
    `include "../uvm/tests/register_file_test.sv"
    
endpackage
